import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-gray-50">
      <body className="min-h-full flex flex-col">
        <header className="bg-white border-b border-gray-200">
          <nav className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
            <a href="/" className="text-xl font-black text-gray-900 tracking-tight">
              Comp<span className="text-blue-600">Intel</span>
            </a>
            <div className="flex gap-6 items-center">
              <a href="/salaries" className="text-sm font-bold text-gray-500 hover:text-blue-600 transition">Salaries</a>
              <a href="/compare" className="text-sm font-bold text-gray-500 hover:text-blue-600 transition">Compare</a>
              <button className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-bold hover:bg-blue-700 transition shadow-sm">
                Submit Salary
              </button>
            </div>
          </nav>
        </header>
        <main className="flex-1">
          {children}
        </main>
        <footer className="bg-white border-t border-gray-200 py-8">
          <div className="max-w-6xl mx-auto px-6 text-center text-gray-400 text-xs font-bold uppercase tracking-widest">
            &copy; 2026 Compensation Intelligence System &bull; India &rarr; Global
          </div>
        </footer>
      </body>
    </html>
  );
}
